/* eslint-disable */
export default async () => {
    const t = {
        ["./user/entities/user.entity"]: await import("./user/entities/user.entity"),
        ["./card/entities/card.entity"]: await import("./card/entities/card.entity"),
        ["./collection/entities/collection.entity"]: await import("./collection/entities/collection.entity"),
        ["./profile/entities/profile.entity"]: await import("./profile/entities/profile.entity")
    };
    return { "@nestjs/swagger": { "models": [[import("./card/entities/card.entity"), { "Card": { id: { required: true, type: () => Number }, term: { required: true, type: () => String }, meaning: { required: true, type: () => String }, author: { required: true, type: () => String } } }], [import("./collection/entities/collection.entity"), { "Collection": { id: { required: true, type: () => Number }, name: { required: true, type: () => String }, user: { required: true, type: () => t["./user/entities/user.entity"].User }, cards: { required: true, type: () => [t["./card/entities/card.entity"].Card] } } }], [import("./user/entities/user.entity"), { "User": { id: { required: true, type: () => Number }, username: { required: true, type: () => String }, password: { required: true, type: () => String }, collections: { required: true, type: () => [t["./collection/entities/collection.entity"].Collection] } } }], [import("./profile/entities/profile.entity"), { "Profile": { id: { required: true, type: () => Number }, email: { required: true, type: () => String }, birthDate: { required: true, type: () => String }, user: { required: true, type: () => t["./user/entities/user.entity"].User } } }], [import("./auth/dto/auth.dto"), { "SignInDto": { username: { required: true, type: () => String }, password: { required: true, type: () => String } } }], [import("./user/dto/user.dto"), { "UserDto": { id: { required: true, type: () => Number }, username: { required: true, type: () => String } } }]], "controllers": [[import("./user/user.controller"), { "UserController": { "getAllUsers": { type: [t["./user/entities/user.entity"].User] }, "createUser": { type: t["./user/entities/user.entity"].User } } }], [import("./card/card.controller"), { "CardController": { "getAllCards": { type: [t["./card/entities/card.entity"].Card] }, "createCard": { type: t["./card/entities/card.entity"].Card }, "findCardByTerm": { type: [t["./card/entities/card.entity"].Card] }, "deleteCard": { type: String }, "updateCard": {} } }], [import("./profile/profile.controller"), { "ProfileController": { "getAllUsers": { type: [t["./profile/entities/profile.entity"].Profile] }, "createUser": { type: t["./profile/entities/profile.entity"].Profile } } }], [import("./collection/collection.controller"), { "CollectionController": { "getAllCollections": { type: [t["./collection/entities/collection.entity"].Collection] }, "addCollection": { type: t["./collection/entities/collection.entity"].Collection }, "findCollectionsByUserId": { type: [t["./collection/entities/collection.entity"].Collection] }, "addCardsToCollection": { type: t["./collection/entities/collection.entity"].Collection } } }], [import("./auth/auth.controller"), { "AuthController": { "signIn": { type: Object } } }]] } };
};